### PR TITLE
query builder plugin for chosen-js

### PR DESCRIPTION
**Pull request by premithk**
**Merge request checklist**

- [ ] I read the [guidelines for contributing](https://github.com/mistic100/jQuery-QueryBuilder/blob/master/.github/CONTRIBUTING.md)
- [ ] I created my branch from `dev` and I am issuing the PR to `dev`
- [ ] Unit tests are OK
- [ ] If it's a new feature, I added the necessary unit tests
- [ ] If it's a new language, I filled the `__locale` and `__author` fields

### CODE REVIEW

**Comment by mistic100** [comment]
Please do not ignore `dist` nor commit `dist` files

**Comment by mistic100** [comment]
Ok it's great but 

- you forgot to add chosen as dependency in the examples bower
- you added select2 but it's not used
- you modified bt-selectbpicker
- the JSDoc of the plugin is wrong (@class, @description, @params)
- the options of the plugins are wrong (copied from bt-selectpicker)
- you do not pass the code style checks
- you didn't added unit tests
- I think it would require a check to ensure "bt-selectpicker" is not enabled too

**Comment by premithk** [comment]
@mistic100 yes, had done this pull request in haste. will fix these and issue a new one

**Comment by premithk** [comment]
I was working on the fixes. Can't find a way to check if bt-selectpicker is also enabled. Can you give me some pointers

**Comment by mistic100** [comment]
```js
if (this.settings.plugins['bt-selectpicker']) { ... }
```

**Comment by premithk** [comment]
Thank you! Will check this out

**Pull request closed without merging**
