### PR TITLE
example of integration with react.js

### PR DESCRIPTION
**Pull request by malaman**
Hi, 
thank you for the wonderful app.
we are using your app in the react application and so far the integration works well for us.
I think, it might be useful for other people to see how the jQuery Query Builder can be integrated in the react infrastructure.

### CODE REVIEW

**Comment by mistic100** [comment]
That's nice but I don't want to take the responsability of maintaining the example.

You can still create a separated repo/fiddle/codepen/other and I will add a link in the doc.

**Comment by malaman** [comment]
I've created separate repo with the example https://github.com/malaman/jQuery-QueryBuilder-react-integration-example.git

**Comment by mistic100** [comment]
> To pass rules info from React component to jQuery-QueryBuilder, it is nessesary to reinitialize jQuery-QueryBuilder app.

Why ? there is the "setRules" method

**Comment by malaman** [comment]
Agree. 'setRules' should be used in this case. I've updated example repo.

**Pull request closed without merging**
