### PR TITLE
Added support for 'boolean' type.

### PR DESCRIPTION
**Pull request by cruzmiraback**

### CODE REVIEW

**Comment by mistic100** [comment]
I don't see the gain over an int. people will always use a radios group or a select for yes/no values so possible values are already filtered

and what if I want yes/no or 1/0 instead of true/false ? (like PHP filter_var() accept)

---

also this
```js
!!(value.trim().toLowerCase() === "true")
```

is useless, same as 
```js
value.trim().toLowerCase() === "true"
```

(and is jshint compliant)

**Comment by cruzmiraback** [comment]
The use case I see this for is when you want to compare against a field of type boolean that ONLY contains true or false values. Currently there doesn't seem to be a way to do this (at least, I can't figure out how). 

For example, I want to do a query and return only the records that contain the field 'foo' with a value of true.
A valid mongo query for this would look like:
{"$and":[{"foo":true}]}

Using int for this won't work, for example:
{"$and":[{"foo":1}]} (Returns 0 records)

Using string for this also doesn't work:
{"$and":[{"foo":"true"}]} (Returns 0 records)

**Comment by mistic100** [comment]
ok I though Mongo accepts ints as bools

but you have a problem in the SQL plugin, without prepared statement the boolean is concatenated to the string, resulting in "true"/"false" and not "1"/"0" (it might work on MySQL but certainly not other DBMS)

---

jshint is still failing, you should run `grunt test` before pushing

---

I won't merge until you or I find a nice solution to also accept (and convert) at least 0 and 1 as raw values

**Comment by mistic100** [comment]
It would be nice if you could squash your commits when done (`rebase -i` then `push --force`)

**Comment by cruzmiraback** [comment]
Thanks!

**Pull request merged**
