### PR TITLE
Puppet support

### PR DESCRIPTION
**Pull request by propyless**
Hello,

I've added a plugin for generating puppet queries.
https://docs.puppetlabs.com/puppetdb/2.3/api/query/v4/query.html

I however edited some defaults in default.js and i'm sure there is another way to do this so that the extra operators are taken from the plugin configuration but since I wasn't sure I did it this way to get it working at least.

If you could help me out with this i'd be quite grateful.
Or if you feel that the extra lines I added to default.js are ok then splendid!

### CODE REVIEW

**Comment by mistic100** [comment]
Sorry I can't accept that.
You added conditions and operators in the default config which will be totally useless for most users. 
A plugin... is a plugin. It must not have to touch the core.

Move everything in `QueryBuilder.defaults` in the plugin file. Also move language strings in the plugin i18n folder.

Don't you think there will be a problem for users when two different operators have the same label ? You should rethink this (I don't know Puppet, I don't know the difference between `equal` and `puppet_equal`).

**Comment by propyless** [comment]
Hello, I wasn't aware I could put lang stuff in the plugin directory and nor that I could specify extra operators into the plugin, I don't think is documented or at least not where I looked. I took a look at the mongodb and sql plugins but they did not do what you described.

I have moved the stuff I changed in the defaults.js to plugin.js and the same functionality seems to be still exist. I will write some unit tests now...

**Comment by mistic100** [comment]
http://mistic100.github.io/jQuery-QueryBuilder/dev/plugins.html
the link to this page is in the main "Plugins" page

**Comment by mistic100** [comment]
don't redefine everything in the language file !  just what you need to add

**Comment by mistic100** [comment]
Still, I would prefer this to be distributed as a standalone plugin, in a separated repo

I don't want to add every possible "translator" in the main repo (mainly because, now I have to maintain them myself)
Loopback is already on the edge and I am considering asking the author to put it elsewhere

**Comment by propyless** [comment]
Hello,

Alright sure I can keep in a separated repository and maintain it myself :)

Thank you for your help!

**Comment by mistic100** [comment]
if you think some adjustments are necessary in the core to ease the integration of external plugin don't hesitate.

For pure JS plugins it's simple, add a RequireJS and you are done :
```js
(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        define(['jquery', 'query-builder'], factory);
    }
    else {
        factory(root.jQuery);
    }
}(this, function($) {
"use strict";

var QueryBuilder = $.fn.queryBuilder;

// ACTUAL CODE

}));
```

For languages, something like (inside above wrapper)

```js
$.extend(true, QueryBuilder.regional.en, {
 // strings
});
```
should work

**Comment by mistic100** [comment]
you can see how https://github.com/fabien/jQuery-QueryBuilder-Loopback works

**Comment by propyless** [comment]
hi mistic, thanks for the tip. I will look into it as soon as i've finished refactoring the plugin to work the way i want it too.

I just have a small question about the nb_inputs.. is it possible to specify it as nargs.
I'm currently using the the input directive in the hash to specify custom inputs but the nb_inputs for the operator has a specific naming convention and i added a button so i can add more inputs. do these "extra" added inputs need to follow the same naming convention? i'm not so sure if i formulated my issue very well.. if you need more information or clarification i can provide a picture or two.

**Comment by mistic100** [comment]
no idea what you mean

**Pull request closed without merging**
