### PR TITLE
bug fix reading "not" from JSON

### PR DESCRIPTION
**Pull request by scoobydubz**
**Merge request checklist**

- [ ] I read the [guidelines for contributing](https://github.com/mistic100/jQuery-QueryBuilder/blob/master/.github/CONTRIBUTING.md)
- [ ] I created my branch from `dev` and I am issuing the PR to `dev`
- [ ] I didn't pushed the `dist` directory
- [ ] Unit tests are OK
- [ ] If it's a new feature, I added the necessary unit tests
- [ ] If it's a new language, I filled the `__locale` and `__author` fields

### CODE REVIEW

**Comment by scoobydubz** [comment]
If any condition group "NOT" buttons are checked then all of them get set to checked upon reloading any saved conditions. I believe this is because I'm using the getRules json to load any saved conditions and the values for "not" are strings..

"not": "true" or "not": "false"

**Comment by Guite** [comment]
For me the original version works, while this PR breaks the functionality.

**Comment by mistic100** [comment]
@scoobydubz the plugin exports the flag as boolean, it is not it's responsability if you change the type

@Guite thank you for testing it

**Comment by scoobydubz** [comment]
Thank you for considering this. The booleans were getting converted to strings when passing the data to the server. I actually ended up having to add the following check to the "jsonToGroup.filter" event in order to get it working everywhere..

```
if (typeof json.not === 'string') {
	e.value.not = json.not == 'true';
} else {
	e.value.not = !!json.not;
}
```

But then, after a little more searching around I found that by using JSON.stringify before passing the data to the server the boolean values were then left alone and all issues were resolved.

That's the proper way to handle this situation. Sorry for trying to blame your plugin!

Thank you!

**Pull request closed without merging**
