### PR TITLE
Modify the library load information being used in the example

### PR DESCRIPTION
**Pull request by ninezero90hy**
In the example, there is a renamed file in the library you are using
I think it's because you didn't lock the package
I'm sure you had a reason why you didn't lock the package, so I quickly fixed the problem

@mistic100 What do you think? 😉

**Merge request checklist**

- [x] I read the [guidelines for contributing](https://github.com/mistic100/jQuery-QueryBuilder/blob/master/.github/CONTRIBUTING.md)
- [x] I created my branch from `dev` and I am issuing the PR to `dev`
- [x] I didn't pushed the `dist` directory
- [ ] Unit tests are OK
- [ ] If it's a new feature, I added the necessary unit tests
- [ ] If it's a new language, I filled the `__locale` and `__author` fields

### CODE REVIEW

**Comment by ninezero90hy** [comment]
I didn't modify the function!
I don't think my change caused me to fail the unit test. :)
No? @mistic100 Is it my problem?

**Comment by mistic100** [comment]
@ninezero90hy tests are failing for month and I never found why (it works on a local computer).

Could you update the version to "^1.0.0" in both the package.json and bower.json (though someday this file will be removed) ?

**Comment by paige0701** [comment]
Are you talking about the jquery-extextext library version?

**Comment by ninezero90hy** [comment]
I didn't understand exactly, but do you mean to change the library version I changed to ^1.0.0?

**Comment by ninezero90hy** [comment]
```json
  "dependencies": {
    ...
    "jquery-extendext": "0.1.2",
    ...
  }
```

I think locking the package is a fundamental solution.
I think that if you don't lock the package, another problem may arise later by another library.
If you don't want to fix the example, I think it's a good idea to fix the `jquery-extendext` version to `0.1.2`.

@mistic100  What do you think?
This is what I think.

I think a lot of people would like to see the samples.

**Comment by ninezero90hy** [comment]
Oh! And I'm just wondering, is there a reason why you don't lock the package?
It's just a question 😉

**Comment by mistic100** [comment]
I think locking the package prevents to get fixes, moreover because QueryBuilder is not released often, and extendext is mine.
The error was to define ">=" but "^" is totally fine.

No it should not be locked to 0.1.2 because this is an outdated version.

**Comment by ninezero90hy** [comment]
I get it! So it's normal to modify it now, right?

**Pull request merged**
