### PR TITLE
Fix for issue #228

### PR DESCRIPTION
**Pull request by ryansmith4**
- see https://github.com/mistic100/jQuery-QueryBuilder/issues/228
- incorporates jscs fixes from prior pull request

### CODE REVIEW

**Comment by mistic100** [comment]
Where is the test suite file ?
You DON'T (and didn't) have to create a new pull, just commit on the same branch.

**Comment by ryansmith4** [comment]
Yup, my bad.  Git best practices seemed to suggest keeping your master branch clean for easier syncing with upstream and to put feature/bug fixes on isolated branches. The new pull request is due to my relative inexperience with git (being mostly familar with hg myself) moving my check-in against master to its own branch and synching with the upstream repository.  It seemed easier to re-fork against the latest source, hence the additional pull.

**Comment by ryansmith4** [comment]
I've re-added the utils test script (utils.module.js)

**Comment by mistic100** [comment]
I must try to find why the travis test sometimes fails when loading Blanket (it's not your fault).

**Pull request merged**
