### PR TITLE
Use verbs for operators, for consistency

### PR DESCRIPTION
**Pull request by smor**
**Merge request checklist**

- [x] I read the [guidelines for contributing](https://github.com/mistic100/jQuery-QueryBuilder/blob/master/.github/CONTRIBUTING.md)
- [x] I created my branch from `dev` and I am issuing the PR to `dev`
- [x] Unit tests are OK
- [x] If it's a new feature, I added the necessary unit tests
- [x] If it's a new language, I filled the `__locale` and `__author` fields

### CODE REVIEW

**Comment by smor** [comment]
All other operators use verbs, so why not those ?

**Comment by mistic100** [comment]
C'est historique :-)

**Comment by mistic100** [comment]
En plus "pas dans" c'était moche. Merci.

**Comment by smor** [comment]
De rien ! :-)

**Pull request merged**
