### PR TITLE
Pass previous operator to afterUpdateRuleOperator event

### PR DESCRIPTION
**Pull request by giero**
Added previousOperator to 'afterUpdateRuleOperator' event - could be useful in some cases ;)

### CODE REVIEW

**Comment by mistic100** [comment]
Could also do it for afterUpdateRuleFilter, afterUpdateRuleValue and afterUpdateGroupCondition ? (these needs to update the method calls on core.js lines 285 and 300)

**Comment by giero** [comment]
I'm on it, but ... updateRuleValue is called also in updateRuleOperator function (just after afterUpdateRuleOperator event) - what should be passed there?
New updateRuleValue will look like this
```javascript
QueryBuilder.prototype.updateRuleValue = function(rule, oldRuleValue) {
...
}
```
but updateRuleOperator doesn;t change rule value ... so ... undefined?

**Comment by giero** [comment]
@mistic100 Is it enough to merge?

**Comment by mistic100** [comment]
@giero there is still a pending review

**Comment by mistic100** [comment]
@giero Sorry the review was not published, I didn't see it because the behavior changed some months ago

**Comment by giero** [comment]
I've changed what you suggested.
It's only few lines of code - why review last so long?

**Pull request merged**
