### PR TITLE
Reconstructing the rules from the mongo query (#73)

### PR DESCRIPTION
**Pull request by cruzmiraback**

### CODE REVIEW

**Comment by cruzmiraback** [comment]
Please review the solution when you have time.

**Comment by mistic100** [comment]
Would you kindly add unit tests for this ?
Thank you

**Comment by cruzmiraback** [comment]
Added unit test to core_tests.js using existing mongo query in data.js.

**Comment by cruzmiraback** [comment]
Something to note is that this function will return only the id, operator, and value attributes. The ID is assumed to be the passed in field name. This seems sufficient to me for most use cases but it could be made more customizable if we added another parameter to the getRulesFromMongo function. This parameter could be an array of objects that contain more information for some or all fields (including overriding the ID).

**Comment by mistic100** [comment]
i refactorized things a bit

--

you are right about id/field and it's a very edge case

I "solved" it by adding a value filter while constructing the rule object
```js
id: that.change('getMongoDBFieldID', field, value)
```

this way there is still a possibility for someone to choose which filter to use based on field and value

---

thank you for your work

**Comment by cruzmiraback** [comment]
Thanks for the merge, nice changes.

**Pull request merged**
