### PR TITLE
Add langs cs ua and az

### PR DESCRIPTION
**Pull request by mborisv**

### CODE REVIEW

**Comment by mistic100** [comment]
Can you add the `__author` field after `__locale` ?

**Comment by mistic100** [comment]
There is also https://github.com/mistic100/jQuery-QueryBuilder/tree/master/src/plugins/invert/i18n

**Comment by mistic100** [comment]
@mborisv bump

**Comment by mborisv** [comment]
Sorry , i was busy, maybe tomorrow will make commit 01.02.2016, 18:40, "Damien Sorel" <notifications@github.com>:@mborisv bump—Reply to this email directly or view it on GitHub.   -- С уважением,Борис Межевитинов7 (905) 519-69-12mborisv@ya.ru

**Comment by mborisv** [comment]
done

**Comment by mistic100** [comment]
Great

**Pull request merged**
