### PR TITLE
Typeahead Support

### PR DESCRIPTION
**Pull request by tomhukins**
Bootstrap-3-Typeahead provides typeahead suggestions for text input fields.  Users can either choose a suggestion or enter arbitrary text:
https://github.com/bassjobsen/Bootstrap-3-Typeahead/

### CODE REVIEW

**Comment by mistic100** [comment]
* Do not access Rule properties via `__` this is for internal usage only http://querybuilder.js.org/#inside_the_box
* The way you access the input is not optimized, you must use `rule.$el.find(Selectors.rule_value)`
* Please add some unit-tests you think relevant (at least check the plugin is effectively loaded), that implies adding the bower component to the `devDependencies` section
* I would have named the plugin simply `bt-typehead`

**Comment by mistic100** [comment]
Well actually I don't this the interest of this, it's exactly the same as using the `plugin` and `plugin_config` options.
I don't see any betterment in this.

**Comment by tomhukins** [comment]
Thank you very much for all your work on this useful tool and your quick reply.

I've been learning a lot about how jQuery-QueryBuilder works but hadn't figured out the simple approach you describe using ``plugin`` and ``plugin_config``.  I just tried using them and everything works exactly as you suggest without needing any new code! :-)

**Comment by mistic100** [comment]
Nice, good luck on your project :-)

**Pull request closed without merging**
