### PR TITLE
added hebrew translation file (he.json)

### PR DESCRIPTION
**Pull request by kfirstri**
Hello :)

I've added a Hebrew translation file to the project.

**Merge request checklist**

- [X] I read the [guidelines for contributing](https://github.com/mistic100/jQuery-QueryBuilder/blob/master/.github/CONTRIBUTING.md)
- [X] I created my branch from `dev` and I am issuing the PR to `dev`
- [X] Unit tests are OK
- [ ] If it's a new feature, I added the necessary unit tests
- [X] If it's a new language, I filled the `__locale` and `__author` fields

### CODE REVIEW

**Comment by kfirstri** [comment]
It's failing cause of line breaks =\ 
i'll see what i can do..

**Comment by mistic100** [comment]
and this https://github.com/mistic100/jQuery-QueryBuilder/tree/dev/src/plugins/invert/i18n

**Comment by mistic100** [comment]
@kfirstri don't worry about the line breaks, can you just translate the two other files ? thank you

**Comment by kfirstri** [comment]
added the Hebrew language selection to the exmaple page, and translated the extra 2 lang files.

**Pull request merged**
