### PR TITLE
Create tr.json

### PR DESCRIPTION
**Pull request by aalpgiray**
Translated to Turkish have a nice day.

### CODE REVIEW

**Comment by mistic100** [comment]
Please change the __author, I'll only allow references to individuals and personal websites/emails, I can't have references to commercial entities

**Comment by mistic100** [comment]
Also there is this https://github.com/mistic100/jQuery-QueryBuilder/tree/master/src/plugins/invert/i18n

**Comment by aalpgiray** [comment]
author parameter changed as mentioned.

**Comment by mistic100** [comment]
Done in addition to #216
Please take time to understand how Git and Github work.

**Comment by aalpgiray** [comment]
Thank you for tolerating the inconvenience. This was my first.  Hava a nice day.

**Pull request merged**
